### ISSUE TITLE
META6.json is absent

### ISSUE THREAD

**Issue by titsuki** [jonathanstowe/EventSource-Client#1]
Hi,
I found that this module isn't installable with zef because of the absence of META6.json:
```
$ zef -v install https://github.com/jonathanstowe/EventSource-Client.git
===> Fetching [OK]: https://github.com/jonathanstowe/EventSource-Client.git to /home/itoyota/.zef/tmp/1517654003.18887.6330/EventSource-Client.git
===> Extraction: Failed to find a META6.json file for https://github.com/jonathanstowe/EventSource-Client.git -- failure is likely
```

**Comment by jonathanstowe** [comment]
Sorry it took me so long to get back.

I'd completely forgotten to commit the META file :-) Should be good now.

I haven't made a formal release of this as yet because I haven't had the time to make some proper unit tests for it.

**Comment by titsuki** [comment]
Thanks for your reply!
